# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8091b9589098be590469ce62bd060e2e5a600868247fd8ac212950d216d32782a20c680430f1c9f5fbe835cf36552696eafbc2e28b96729c82374d3b0ab05b4

test:
  secret_key_base: bb9a613ee9ec0e1a101441f3d1ffe6b2b06a7bdb37400d07427b21a193a760557e1905e0d8eb7c37868385e8894bff2e3a9cfbf5fc5c7ee3900d0270b351638d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
